logging:
  file:
    name: /CDCNonCNN/log/CDCSonCNN-prod.log
  level:
    cn.doublefloat.CDCSonCNN: warn
    org.springframework: warn


project:
  path: /CDCSonCNN/project

docker:
  url: "39.107.70.247"
  port: 2375
  certsPath: "/CDCSonCNN/certs"